# Generated by Django 4.1 on 2023-02-15 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteleria_model',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
