# Generated by Django 4.1 on 2023-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0002_alter_pasteleria_model_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasteleria_model',
            name='descripcion',
        ),
    ]
