# Generated by Django 4.1 on 2023-02-15 17:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0003_remove_pasteleria_model_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteleria_model',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
