# Generated by Django 4.1 on 2023-02-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0004_pasteleria_model_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteleria_model',
            name='precio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
