# Generated by Django 4.1 on 2023-02-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0005_alter_pasteleria_model_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteleria_model',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
