# Generated by Django 4.1 on 2023-02-16 16:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0006_alter_pasteleria_model_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteleria_model',
            name='imagen',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
