# Generated by Django 4.1 on 2023-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0008_alter_pasteleria_model_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasteleria_model',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Pasteleria', 'Pasteleria'), ('Salados', 'Salados'), ('Bebidas', 'Bebida'), ('Brunch', 'Brunch'), ('Cafes', 'Cafes')], default='Pasteleria', max_length=15, null=True),
        ),
    ]
