# Generated by Django 4.1 on 2023-02-17 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0009_pasteleria_model_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteleria_model',
            name='imagen',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
