# Generated by Django 4.1 on 2023-02-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0010_alter_pasteleria_model_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteleria_model',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
