# Generated by Django 4.1 on 2023-02-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0013_salados_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasteleria_model',
            name='categoria',
        ),
    ]
