# Generated by Django 4.1 on 2023-02-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0016_bebidas_cafes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bebidas_cafes',
            new_name='cafes_model',
        ),
    ]
