# Generated by Django 4.1 on 2023-02-19 15:13

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0017_rename_bebidas_cafes_cafes_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='brunch_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, max_length=100, null=True)),
                ('precio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
