# Generated by Django 4.1 on 2023-02-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0018_brunch_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch_model',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
