# Generated by Django 4.1 on 2023-02-19 15:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0019_alter_brunch_model_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch_model',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=100, null=True),
        ),
    ]
