# Generated by Django 4.1.7 on 2023-02-23 20:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0020_alter_brunch_model_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch_model',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pasteleria_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
