# Generated by Django 4.1.7 on 2023-02-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0024_alter_pasteleria_model_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bebidas/'),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='brunchs/'),
        ),
        migrations.AlterField(
            model_name='cafes_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/'),
        ),
        migrations.AlterField(
            model_name='pasteleria_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pasteleria/'),
        ),
        migrations.AlterField(
            model_name='salados_model',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='salados/'),
        ),
    ]
