# Generated by Django 4.1.7 on 2023-02-28 16:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0025_alter_bebidas_model_imagen_alter_brunch_model_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='populares_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pasteleria/')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('precio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
