# Generated by Django 4.1.7 on 2023-02-28 16:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0026_populares_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafes_model',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
    ]
