# Generated by Django 4.1.7 on 2023-02-28 20:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0028_rename_info_cafes_model_informacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populares_model',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='bebidas_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brunch_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pasteleria_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salados_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
    ]
