# Generated by Django 4.1.7 on 2023-03-12 01:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0029_remove_populares_model_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name='cafes_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name='pasteleria_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name='populares_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name='salados_model',
            name='informacion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=184, null=True),
        ),
    ]
