# Generated by Django 4.1.7 on 2023-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0030_alter_bebidas_model_informacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas_model',
            name='titulo',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='titulo',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='cafes_model',
            name='titulo',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='pasteleria_model',
            name='informacion',
            field=models.CharField(blank=True, max_length=184, null=True),
        ),
        migrations.AlterField(
            model_name='populares_model',
            name='titulo',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='salados_model',
            name='titulo',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
