# Generated by Django 4.1.7 on 2023-03-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0031_alter_bebidas_model_titulo_alter_brunch_model_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch_model',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='brunch_model',
            name='informacion',
            field=models.CharField(blank=True, max_length=184, null=True),
        ),
    ]
