# Generated by Django 4.1.7 on 2023-03-12 21:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almendra_app', '0032_alter_brunch_model_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch_model',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True),
        ),
    ]
